from datetime import datetime, timezone
import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool
from fastapi.testclient import TestClient

from constants import get_current_user, hash_password
from rest_api import app
from database import get_db
from models.rds_models import Base, User
from storages.rds_storage_implementation import RDSStorageImplementation
from tests.factories.base import BaseFactory
from tests.factories.dtos import UserCreateFactory, UserLoginFactory, UpdateUserDTOFactory
from tests.factories.models import UserFactory

SQLALCHEMY_DATABASE_URL = "sqlite:///:memory:"
engine = create_engine(SQLALCHEMY_DATABASE_URL, connect_args={"check_same_thread": False}, poolclass=StaticPool)
TestingSessionLocal = sessionmaker(bind=engine)

def override_get_db_local():
    try:
        db = TestingSessionLocal()
        yield db
    finally:
        db.close()

@pytest.fixture(scope="session", autouse=True)
def setup_db():
    Base.metadata.create_all(bind=engine)
    yield engine
    Base.metadata.drop_all(bind=engine)

@pytest.fixture(scope="function")
def db():
    session = TestingSessionLocal()
    try:
        yield session
    finally:
        session.rollback()
        # Clean up all tables to ensure isolation since we use StaticPool (shared memory)
        for table in reversed(Base.metadata.sorted_tables):
            session.execute(table.delete())
        session.commit()
        session.close()

@pytest.fixture(scope="function")
def client(db):
    def override_get_current_user():
        return "test_user"
    app.dependency_overrides[get_db] = override_get_db_local
    app.dependency_overrides[get_current_user] = override_get_current_user
    with TestClient(app) as client:
        yield client
    app.dependency_overrides.clear()

@pytest.mark.asyncio
async def test_register_user(db, client):
    # Arrange
    user_info = UserCreateFactory()
    payload = user_info.model_dump()

    # Act
    # Remove autogenerated fields that shouldn't be in request if any, but UserCreate usually is clean.
    # Looking at factory, it has all fields. login/register usually just needs user/pass. 
    # But UserCreate matches the Pydantic schema used in the route.
    response = client.post("/register", json=payload)

    # Assert
    assert response.status_code == 201
    
    # Verify in DB
    user = db.query(User).filter_by(username=payload['username']).first()
    assert user is not None
    assert user.email == payload['email']

@pytest.mark.asyncio
async def test_login(db, client):
    # Arrange
    password = "password123"
    # Create user in DB first with hashed password
    hashed_password = hash_password(password)
    user = UserFactory(password=hashed_password)
    
    # Create login payload with plain password
    user_login = UserLoginFactory(username=user.username, password=password)
    
    # Act
    response = client.post("/login", json=user_login.model_dump())
    
    # Assert
    assert response.status_code == 200
    # Assuming login returns some JSON.
    # response.json()

@pytest.mark.asyncio
async def test_get_user_profile(db, client):
    # Arrange
    # "test_user" is the username returned by override_get_current_user
    username = "test_user"
    user = UserFactory(username=username)

    # Act
    response = client.get("/user/")

    # Assert
    assert response.status_code == 200
    data = response.json()
    assert data["username"] == user.username
    assert data["email"] == user.email

@pytest.mark.asyncio
async def test_when_user_profile_not_present_user_not_found(db, client):
    # Arrange
    username = "non_existent_user"
    user = UserFactory()

    # Act
    response = client.get("/user/")

    # Assert
    assert response.status_code == 404
    assert response.json() == {"detail": "User not found"}

@pytest.mark.asyncio
async def test_update_user_profile(db, client):
    # Arrange
    username = "test_user"
    user = UserFactory(username=username)
    update_data = UpdateUserDTOFactory()

    # Act
    response = client.put("/user/", json=update_data.model_dump())

    # Assert
    assert response.status_code == 200
    data = response.json()
    assert data["fullname"] == update_data.fullname
    assert data["email"] == update_data.email
    
    # Verify in DB
    db.refresh(user)
    assert user.fullname == update_data.fullname

@pytest.mark.asyncio
async def test_get_all_users(db, client):
    # Arrange
    # Create a few users
    UserFactory.create_batch(3)
    # Ensure current user is also one of them (factory logic handled separately)
    # Total at least 3

    # Act
    response = client.get("/user-details/")

    # Assert
    assert response.status_code == 200
    data = response.json()
    assert len(data) >= 3
@pytest.mark.asyncio
async def test_storage_register_user(db):
    # Arrange
    user_info = UserCreateFactory(username="new_storage_user", email="new@storage.com")
    storage = RDSStorageImplementation(db)

    # Act
    await storage.register_user(user_info)

    # Assert
    user = db.query(User).filter_by(username="new_storage_user").first()
    assert user is not None
    assert user.email == "new@storage.com"

@pytest.mark.asyncio
async def test_storage_login(db):
    # Arrange
    password = "password123"
    hashed = hash_password(password)
    # Manually create user to ensure password hash matches logic if factories don't hash
    user = UserFactory(username="login_user", password=hashed) 
    
    # Note: RDSStorageImplementation.login calls hash_password on the input password.
    # So if we store hashed password in DB, login with plain password "password123" should work.
    
    storage = RDSStorageImplementation(db)
    user_login = UserLoginFactory(username=user.username, password=password)

    # Act
    response = await storage.login(user_login)

    # Assert
    assert "access_token" in response
    assert response["message"] == f"User logged in successfully: {user.username}"

@pytest.mark.asyncio
async def test_storage_get_user_profile(db):
    # Arrange
    user = UserFactory()
    storage = RDSStorageImplementation(db)

    # Act
    profile = await storage.get_user_profile(user.username)

    # Assert
    assert profile.username == user.username
    assert profile.email == user.email

@pytest.mark.asyncio
async def test_storage_update_user_profile(db):
    # Arrange
    user = UserFactory()
    storage = RDSStorageImplementation(db)
    update_dto = UpdateUserDTOFactory()

    # Act
    updated_user = await storage.update_user_profile(update_dto, user.username)

    # Assert
    assert updated_user.fullname == update_dto.fullname
    assert updated_user.email == update_dto.email
    
    # Verify DB
    db.refresh(user)
    assert user.fullname == update_dto.fullname

@pytest.mark.asyncio
async def test_storage_get_all_users(db):
    # Arrange
    UserFactory.create_batch(3)
    storage = RDSStorageImplementation(db)

    # Act
    users = await storage.get_all_users()

    # Assert
    assert len(users) >= 3
